# Generated by Django 3.1 on 2021-06-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awsDemo', '0002_commande'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
